#!/bin/sh
# Onion-сервис Nyxo: tor публикует v3-адрес, socat пробрасывает соединения
# из tor в приложение по private network Railway. Подробности — README.md.
#
# Почему socat, а не HiddenServicePort прямо на приложение: HiddenServicePort
# принимает только IP, а IP приложения в private network Railway может
# смениться при редеплое. socat с fork резолвит TARGET_HOST заново на каждое
# соединение.
set -eu

LISTEN_PORT=8080
DATA_DIR=/var/lib/tor/data
TOR_USER=debian-tor
SOCAT_USER=nobody
SOCAT_GROUP=nogroup

log() { echo "[tor-service] $*"; }
die() { echo "[tor-service] ОШИБКА: $*" >&2; exit 1; }

TARGET_HOST=${TARGET_HOST:-}
TARGET_PORT=${TARGET_PORT:-}
TARGET_IP_FAMILY=${TARGET_IP_FAMILY:-}
TOR_SINGLE_ONION=${TOR_SINGLE_ONION:-false}
MAX_CONNECTIONS=${MAX_CONNECTIONS:-512}

# Значения подставляются в адрес socat, где ',' и ':' задают опции, —
# опечатка в переменной не должна превращаться в чужую опцию socat.
[ -n "$TARGET_HOST" ] || die "не задан TARGET_HOST (например, nyxo.railway.internal)"
case "$TARGET_HOST" in
    *[!A-Za-z0-9.-]*) die "TARGET_HOST: допустимы только буквы, цифры, '.' и '-' (DNS-имя или IPv4)" ;;
esac
case "$TARGET_PORT" in
    ''|*[!0-9]*) die "TARGET_PORT должен быть внутренним onion-портом приложения (его ONION_PORT)" ;;
esac
[ "$TARGET_PORT" -ge 1 ] && [ "$TARGET_PORT" -le 65535 ] || die "TARGET_PORT вне диапазона 1..65535"
case "$MAX_CONNECTIONS" in
    ''|*[!0-9]*) die "MAX_CONNECTIONS должен быть целым числом" ;;
esac
[ "$MAX_CONNECTIONS" -ge 1 ] || die "MAX_CONNECTIONS должен быть не меньше 1"
case "$TARGET_IP_FAMILY" in
    '') SOCAT_TARGET=TCP ;;
    4) SOCAT_TARGET=TCP4 ;;
    6) SOCAT_TARGET=TCP6 ;;
    *) die "TARGET_IP_FAMILY: пусто (авто), 4 или 6" ;;
esac

# У Single Onion свой каталог и свой адрес: по документации tor каталог,
# однажды использованный в SingleHopMode, нельзя снова использовать для
# обычного (анонимного) onion-сервиса. Переключение режима = новый адрес.
case "$TOR_SINGLE_ONION" in
    true) HS_DIR=/var/lib/tor/nyxo-single ;;
    false) HS_DIR=/var/lib/tor/nyxo ;;
    *) die "TOR_SINGLE_ONION: true или false" ;;
esac

if [ "$(id -u)" = 0 ]; then
    # Railway монтирует volume от root, поэтому права на /var/lib/tor
    # выставляются здесь, а сами tor и socat запускаются уже без root:
    # tor — от debian-tor (единственный, кто видит ключи onion-адреса),
    # socat — от nobody. no_new_privs запрещает вернуть привилегии через setuid.
    mkdir -p "$HS_DIR" "$DATA_DIR"
    chown -R "$TOR_USER:$TOR_USER" /var/lib/tor
    chmod -R go-rwx /var/lib/tor
    chmod 700 /var/lib/tor "$HS_DIR" "$DATA_DIR"
    AS_TOR="setpriv --reuid=$TOR_USER --regid=$TOR_USER --clear-groups --no-new-privs"
    AS_SOCAT="setpriv --reuid=$SOCAT_USER --regid=$SOCAT_GROUP --clear-groups --no-new-privs"
else
    # Контейнер уже запущен не от root: права на volume должны быть
    # выставлены заранее, иначе tor откажется стартовать.
    mkdir -p "$HS_DIR" "$DATA_DIR" && chmod 700 /var/lib/tor "$HS_DIR" "$DATA_DIR" ||
        die "нет прав на /var/lib/tor у пользователя $(id -un); запустите контейнер от root или выдайте права на volume"
    AS_TOR=
    AS_SOCAT=
fi

# torrc собирается при каждом старте (комментарии — здесь, а не в нём).
# HiddenServiceMaxStreams: одному circuit'у (одному клиенту) — не больше 64
# одновременных соединений. Каждое стоит процесса socat, и без лимита один
# клиент мог бы выбрать их все; превысивший лимит circuit закрывается.
TORRC=$(mktemp)
cat > "$TORRC" <<EOF
# generated by nyxo tor-service entrypoint
DataDirectory $DATA_DIR
SocksPort 0
Log notice stdout
HiddenServiceDir $HS_DIR
HiddenServiceVersion 3
HiddenServicePort 80 127.0.0.1:$LISTEN_PORT
HiddenServiceMaxStreams 64
HiddenServiceMaxStreamsCloseCircuit 1
EOF
if [ "$TOR_SINGLE_ONION" = true ]; then
    cat >> "$TORRC" <<EOF
HiddenServiceNonAnonymousMode 1
HiddenServiceSingleHopMode 1
EOF
    log "ВНИМАНИЕ: режим Single Onion — местоположение сервиса не скрывается (клиенты остаются анонимными)"
fi
chmod 644 "$TORRC"

tor_pid=
socat_pid=

stop_children() {
    for pid in $tor_pid $socat_pid; do kill -TERM "$pid" 2>/dev/null || true; done
    for pid in $tor_pid $socat_pid; do wait "$pid" 2>/dev/null || true; done
}

on_signal() {
    trap - TERM INT
    log "получен сигнал остановки, завершаем tor и socat"
    stop_children
    exit 0
}
trap on_signal TERM INT

# -T 600: соединение без трафика 10 минут закрывается — иначе зависшие
# соединения постепенно заняли бы все MAX_CONNECTIONS. Живой Socket.io
# пингует каждые ~25 секунд, его это не задевает.
# shellcheck disable=SC2086 # AS_SOCAT/AS_TOR намеренно разбиваются на слова
$AS_SOCAT socat -T 600 \
    "TCP-LISTEN:$LISTEN_PORT,bind=127.0.0.1,fork,reuseaddr,nodelay,max-children=$MAX_CONNECTIONS" \
    "$SOCAT_TARGET:$TARGET_HOST:$TARGET_PORT,nodelay" &
socat_pid=$!

# shellcheck disable=SC2086
$AS_TOR tor -f "$TORRC" &
tor_pid=$!

log "проброс onion:80 -> $TARGET_HOST:$TARGET_PORT"

# POSIX sh не умеет "wait -n", поэтому раз в 2 секунды проверяем, живы ли
# оба процесса. Если упал любой — завершаем контейнер с ошибкой, и Railway
# перезапустит его целиком (onion без socat или socat без tor бесполезны).
# "sleep & wait" вместо простого sleep — чтобы сигнал остановки
# обрабатывался сразу, а не после пробуждения.
announced=
while kill -0 "$tor_pid" 2>/dev/null && kill -0 "$socat_pid" 2>/dev/null; do
    if [ -z "$announced" ] && [ -s "$HS_DIR/hostname" ]; then
        announced=$(cat "$HS_DIR/hostname")
        log "onion-адрес: $announced"
        log "впишите его в переменную ONION_ADDRESS приложения (без http://)"
    fi
    sleep 2 &
    wait $! || true
done

if kill -0 "$tor_pid" 2>/dev/null; then
    log "socat неожиданно завершился"
else
    log "tor неожиданно завершился"
fi
trap - TERM INT
stop_children
exit 1
